import './tasks/browserify';
import './tasks/build';
import './tasks/changelog';
import './tasks/clean';
import './tasks/default';
import './tasks/enforce';
import './tasks/lint';
import './tasks/release';
import './tasks/test';
